/*
1Click Swap API

API for One-Click Swaps

API version: 0.1.10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oneclick

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AnyInputQuoteWithdrawal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnyInputQuoteWithdrawal{}

// AnyInputQuoteWithdrawal struct for AnyInputQuoteWithdrawal
type AnyInputQuoteWithdrawal struct {
	// Withdrawal status
	Status string `json:"status"`
	// Amount out in readable format
	AmountOutFormatted string `json:"amountOutFormatted"`
	// Amount out in USD
	AmountOutUsd string `json:"amountOutUsd"`
	// Amount out in smallest unit
	AmountOut string `json:"amountOut"`
	// Withdrawal fee in readable format
	WithdrawFeeFormatted string `json:"withdrawFeeFormatted"`
	// Withdrawal fee in smallest unit
	WithdrawFee string `json:"withdrawFee"`
	// Withdrawal fee in USD
	WithdrawFeeUsd string `json:"withdrawFeeUsd"`
	// Timestamp of withdrawal
	Timestamp string `json:"timestamp"`
	// Transaction hash
	Hash string `json:"hash"`
}

type _AnyInputQuoteWithdrawal AnyInputQuoteWithdrawal

// NewAnyInputQuoteWithdrawal instantiates a new AnyInputQuoteWithdrawal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnyInputQuoteWithdrawal(status string, amountOutFormatted string, amountOutUsd string, amountOut string, withdrawFeeFormatted string, withdrawFee string, withdrawFeeUsd string, timestamp string, hash string) *AnyInputQuoteWithdrawal {
	this := AnyInputQuoteWithdrawal{}
	this.Status = status
	this.AmountOutFormatted = amountOutFormatted
	this.AmountOutUsd = amountOutUsd
	this.AmountOut = amountOut
	this.WithdrawFeeFormatted = withdrawFeeFormatted
	this.WithdrawFee = withdrawFee
	this.WithdrawFeeUsd = withdrawFeeUsd
	this.Timestamp = timestamp
	this.Hash = hash
	return &this
}

// NewAnyInputQuoteWithdrawalWithDefaults instantiates a new AnyInputQuoteWithdrawal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnyInputQuoteWithdrawalWithDefaults() *AnyInputQuoteWithdrawal {
	this := AnyInputQuoteWithdrawal{}
	return &this
}

// GetStatus returns the Status field value
func (o *AnyInputQuoteWithdrawal) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AnyInputQuoteWithdrawal) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AnyInputQuoteWithdrawal) SetStatus(v string) {
	o.Status = v
}

// GetAmountOutFormatted returns the AmountOutFormatted field value
func (o *AnyInputQuoteWithdrawal) GetAmountOutFormatted() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AmountOutFormatted
}

// GetAmountOutFormattedOk returns a tuple with the AmountOutFormatted field value
// and a boolean to check if the value has been set.
func (o *AnyInputQuoteWithdrawal) GetAmountOutFormattedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountOutFormatted, true
}

// SetAmountOutFormatted sets field value
func (o *AnyInputQuoteWithdrawal) SetAmountOutFormatted(v string) {
	o.AmountOutFormatted = v
}

// GetAmountOutUsd returns the AmountOutUsd field value
func (o *AnyInputQuoteWithdrawal) GetAmountOutUsd() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AmountOutUsd
}

// GetAmountOutUsdOk returns a tuple with the AmountOutUsd field value
// and a boolean to check if the value has been set.
func (o *AnyInputQuoteWithdrawal) GetAmountOutUsdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountOutUsd, true
}

// SetAmountOutUsd sets field value
func (o *AnyInputQuoteWithdrawal) SetAmountOutUsd(v string) {
	o.AmountOutUsd = v
}

// GetAmountOut returns the AmountOut field value
func (o *AnyInputQuoteWithdrawal) GetAmountOut() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AmountOut
}

// GetAmountOutOk returns a tuple with the AmountOut field value
// and a boolean to check if the value has been set.
func (o *AnyInputQuoteWithdrawal) GetAmountOutOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountOut, true
}

// SetAmountOut sets field value
func (o *AnyInputQuoteWithdrawal) SetAmountOut(v string) {
	o.AmountOut = v
}

// GetWithdrawFeeFormatted returns the WithdrawFeeFormatted field value
func (o *AnyInputQuoteWithdrawal) GetWithdrawFeeFormatted() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WithdrawFeeFormatted
}

// GetWithdrawFeeFormattedOk returns a tuple with the WithdrawFeeFormatted field value
// and a boolean to check if the value has been set.
func (o *AnyInputQuoteWithdrawal) GetWithdrawFeeFormattedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WithdrawFeeFormatted, true
}

// SetWithdrawFeeFormatted sets field value
func (o *AnyInputQuoteWithdrawal) SetWithdrawFeeFormatted(v string) {
	o.WithdrawFeeFormatted = v
}

// GetWithdrawFee returns the WithdrawFee field value
func (o *AnyInputQuoteWithdrawal) GetWithdrawFee() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WithdrawFee
}

// GetWithdrawFeeOk returns a tuple with the WithdrawFee field value
// and a boolean to check if the value has been set.
func (o *AnyInputQuoteWithdrawal) GetWithdrawFeeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WithdrawFee, true
}

// SetWithdrawFee sets field value
func (o *AnyInputQuoteWithdrawal) SetWithdrawFee(v string) {
	o.WithdrawFee = v
}

// GetWithdrawFeeUsd returns the WithdrawFeeUsd field value
func (o *AnyInputQuoteWithdrawal) GetWithdrawFeeUsd() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WithdrawFeeUsd
}

// GetWithdrawFeeUsdOk returns a tuple with the WithdrawFeeUsd field value
// and a boolean to check if the value has been set.
func (o *AnyInputQuoteWithdrawal) GetWithdrawFeeUsdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WithdrawFeeUsd, true
}

// SetWithdrawFeeUsd sets field value
func (o *AnyInputQuoteWithdrawal) SetWithdrawFeeUsd(v string) {
	o.WithdrawFeeUsd = v
}

// GetTimestamp returns the Timestamp field value
func (o *AnyInputQuoteWithdrawal) GetTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *AnyInputQuoteWithdrawal) GetTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *AnyInputQuoteWithdrawal) SetTimestamp(v string) {
	o.Timestamp = v
}

// GetHash returns the Hash field value
func (o *AnyInputQuoteWithdrawal) GetHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hash
}

// GetHashOk returns a tuple with the Hash field value
// and a boolean to check if the value has been set.
func (o *AnyInputQuoteWithdrawal) GetHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hash, true
}

// SetHash sets field value
func (o *AnyInputQuoteWithdrawal) SetHash(v string) {
	o.Hash = v
}

func (o AnyInputQuoteWithdrawal) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnyInputQuoteWithdrawal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["amountOutFormatted"] = o.AmountOutFormatted
	toSerialize["amountOutUsd"] = o.AmountOutUsd
	toSerialize["amountOut"] = o.AmountOut
	toSerialize["withdrawFeeFormatted"] = o.WithdrawFeeFormatted
	toSerialize["withdrawFee"] = o.WithdrawFee
	toSerialize["withdrawFeeUsd"] = o.WithdrawFeeUsd
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["hash"] = o.Hash
	return toSerialize, nil
}

func (o *AnyInputQuoteWithdrawal) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"amountOutFormatted",
		"amountOutUsd",
		"amountOut",
		"withdrawFeeFormatted",
		"withdrawFee",
		"withdrawFeeUsd",
		"timestamp",
		"hash",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnyInputQuoteWithdrawal := _AnyInputQuoteWithdrawal{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAnyInputQuoteWithdrawal)

	if err != nil {
		return err
	}

	*o = AnyInputQuoteWithdrawal(varAnyInputQuoteWithdrawal)

	return err
}

type NullableAnyInputQuoteWithdrawal struct {
	value *AnyInputQuoteWithdrawal
	isSet bool
}

func (v NullableAnyInputQuoteWithdrawal) Get() *AnyInputQuoteWithdrawal {
	return v.value
}

func (v *NullableAnyInputQuoteWithdrawal) Set(val *AnyInputQuoteWithdrawal) {
	v.value = val
	v.isSet = true
}

func (v NullableAnyInputQuoteWithdrawal) IsSet() bool {
	return v.isSet
}

func (v *NullableAnyInputQuoteWithdrawal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnyInputQuoteWithdrawal(val *AnyInputQuoteWithdrawal) *NullableAnyInputQuoteWithdrawal {
	return &NullableAnyInputQuoteWithdrawal{value: val, isSet: true}
}

func (v NullableAnyInputQuoteWithdrawal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnyInputQuoteWithdrawal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
