/*
1Click Swap API

API for One-Click Swaps

API version: 0.1.10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oneclick

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetAnyInputQuoteWithdrawals type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAnyInputQuoteWithdrawals{}

// GetAnyInputQuoteWithdrawals struct for GetAnyInputQuoteWithdrawals
type GetAnyInputQuoteWithdrawals struct {
	// ID of the destination asset.
	Asset string `json:"asset"`
	// Recipient address
	Recipient string `json:"recipient"`
	// Affiliate recipient address
	AffiliateRecipient string `json:"affiliateRecipient"`
	// Details of withdrawals
	Withdrawals *AnyInputQuoteWithdrawal `json:"withdrawals,omitempty"`
}

type _GetAnyInputQuoteWithdrawals GetAnyInputQuoteWithdrawals

// NewGetAnyInputQuoteWithdrawals instantiates a new GetAnyInputQuoteWithdrawals object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAnyInputQuoteWithdrawals(asset string, recipient string, affiliateRecipient string) *GetAnyInputQuoteWithdrawals {
	this := GetAnyInputQuoteWithdrawals{}
	this.Asset = asset
	this.Recipient = recipient
	this.AffiliateRecipient = affiliateRecipient
	return &this
}

// NewGetAnyInputQuoteWithdrawalsWithDefaults instantiates a new GetAnyInputQuoteWithdrawals object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAnyInputQuoteWithdrawalsWithDefaults() *GetAnyInputQuoteWithdrawals {
	this := GetAnyInputQuoteWithdrawals{}
	return &this
}

// GetAsset returns the Asset field value
func (o *GetAnyInputQuoteWithdrawals) GetAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *GetAnyInputQuoteWithdrawals) GetAssetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *GetAnyInputQuoteWithdrawals) SetAsset(v string) {
	o.Asset = v
}

// GetRecipient returns the Recipient field value
func (o *GetAnyInputQuoteWithdrawals) GetRecipient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value
// and a boolean to check if the value has been set.
func (o *GetAnyInputQuoteWithdrawals) GetRecipientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recipient, true
}

// SetRecipient sets field value
func (o *GetAnyInputQuoteWithdrawals) SetRecipient(v string) {
	o.Recipient = v
}

// GetAffiliateRecipient returns the AffiliateRecipient field value
func (o *GetAnyInputQuoteWithdrawals) GetAffiliateRecipient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AffiliateRecipient
}

// GetAffiliateRecipientOk returns a tuple with the AffiliateRecipient field value
// and a boolean to check if the value has been set.
func (o *GetAnyInputQuoteWithdrawals) GetAffiliateRecipientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AffiliateRecipient, true
}

// SetAffiliateRecipient sets field value
func (o *GetAnyInputQuoteWithdrawals) SetAffiliateRecipient(v string) {
	o.AffiliateRecipient = v
}

// GetWithdrawals returns the Withdrawals field value if set, zero value otherwise.
func (o *GetAnyInputQuoteWithdrawals) GetWithdrawals() AnyInputQuoteWithdrawal {
	if o == nil || IsNil(o.Withdrawals) {
		var ret AnyInputQuoteWithdrawal
		return ret
	}
	return *o.Withdrawals
}

// GetWithdrawalsOk returns a tuple with the Withdrawals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAnyInputQuoteWithdrawals) GetWithdrawalsOk() (*AnyInputQuoteWithdrawal, bool) {
	if o == nil || IsNil(o.Withdrawals) {
		return nil, false
	}
	return o.Withdrawals, true
}

// HasWithdrawals returns a boolean if a field has been set.
func (o *GetAnyInputQuoteWithdrawals) HasWithdrawals() bool {
	if o != nil && !IsNil(o.Withdrawals) {
		return true
	}

	return false
}

// SetWithdrawals gets a reference to the given AnyInputQuoteWithdrawal and assigns it to the Withdrawals field.
func (o *GetAnyInputQuoteWithdrawals) SetWithdrawals(v AnyInputQuoteWithdrawal) {
	o.Withdrawals = &v
}

func (o GetAnyInputQuoteWithdrawals) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAnyInputQuoteWithdrawals) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["asset"] = o.Asset
	toSerialize["recipient"] = o.Recipient
	toSerialize["affiliateRecipient"] = o.AffiliateRecipient
	if !IsNil(o.Withdrawals) {
		toSerialize["withdrawals"] = o.Withdrawals
	}
	return toSerialize, nil
}

func (o *GetAnyInputQuoteWithdrawals) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"asset",
		"recipient",
		"affiliateRecipient",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetAnyInputQuoteWithdrawals := _GetAnyInputQuoteWithdrawals{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetAnyInputQuoteWithdrawals)

	if err != nil {
		return err
	}

	*o = GetAnyInputQuoteWithdrawals(varGetAnyInputQuoteWithdrawals)

	return err
}

type NullableGetAnyInputQuoteWithdrawals struct {
	value *GetAnyInputQuoteWithdrawals
	isSet bool
}

func (v NullableGetAnyInputQuoteWithdrawals) Get() *GetAnyInputQuoteWithdrawals {
	return v.value
}

func (v *NullableGetAnyInputQuoteWithdrawals) Set(val *GetAnyInputQuoteWithdrawals) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAnyInputQuoteWithdrawals) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAnyInputQuoteWithdrawals) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAnyInputQuoteWithdrawals(val *GetAnyInputQuoteWithdrawals) *NullableGetAnyInputQuoteWithdrawals {
	return &NullableGetAnyInputQuoteWithdrawals{value: val, isSet: true}
}

func (v NullableGetAnyInputQuoteWithdrawals) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAnyInputQuoteWithdrawals) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
